/*
 *   Copyright (C) <2012>  <Raith Thomas>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.

 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package muc;

/**
 *
 * @author Thomas Raith
 */

import java.awt.Color;
import java.io.*;
import java.net.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MUC_GUI extends javax.swing.JFrame {

    /**
     * Creates new form MUC_GUI
     */
    public MUC_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username_textfield = new javax.swing.JTextField();
        check_button = new javax.swing.JButton();
        check_solution = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        close_button = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        donate_item = new javax.swing.JMenuItem();
        license_item = new javax.swing.JMenuItem();
        about_menue_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Minecraft Username Check v1.0.1");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Minecraft Username Check");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username: ");

        username_textfield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_textfieldKeyReleased(evt);
            }
        });

        check_button.setText("Check");
        check_button.setEnabled(false);
        check_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_buttonMouseClicked(evt);
            }
        });

        check_solution.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu1.setText("File");

        close_button.setText("Close");
        close_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_buttonActionPerformed(evt);
            }
        });
        jMenu1.add(close_button);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        donate_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muc/paypal-icon.png"))); // NOI18N
        donate_item.setText("Donate");
        donate_item.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        donate_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donate_itemActionPerformed(evt);
            }
        });
        jMenu2.add(donate_item);

        license_item.setText("License");
        license_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                license_itemActionPerformed(evt);
            }
        });
        jMenu2.add(license_item);

        about_menue_item.setText("About");
        about_menue_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_menue_itemActionPerformed(evt);
            }
        });
        jMenu2.add(about_menue_item);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(username_textfield)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 63, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(check_solution)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(check_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(check_button, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_solution))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        username_textfield.getAccessibleContext().setAccessibleName("username_to_check");
        check_button.getAccessibleContext().setAccessibleName("check_button");
        check_button.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void username_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_textfieldKeyReleased
        if (!"".equals(username_textfield.getText()))
            check_button.setEnabled(true);
        else
            check_button.setEnabled(false);
    }//GEN-LAST:event_username_textfieldKeyReleased

    private void check_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_buttonMouseClicked
        URL url = null;
        BufferedInputStream bufferedInput = null;
        byte[] buffer = new byte[1024];
        check_solution.setForeground(Color.black);
        check_solution.setText("checking...");
        
        try {
            url = new URL("http://www.minecraft.net/haspaid.jsp?user=" + username_textfield.getText());
        } catch (MalformedURLException ex) {
            Logger.getLogger(MUC_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            bufferedInput = new BufferedInputStream(url.openStream());
            int bytesRead = 0;
             while ((bytesRead = bufferedInput.read(buffer)) != -1) {
                
                String chunk = new String(buffer, 0, bytesRead);
                System.out.println(chunk);
                if ("true".equals(chunk))
                {
                    check_solution.setForeground(Color.black);
                    check_solution.setText("This Minecraft - account ist valid");
                }
                else
                {
                    check_solution.setForeground(Color.red);
                    check_solution.setText("This Minecraft - account ist not valid");
                }
             }
                bufferedInput.close();
            
        } 
        catch (IOException ex) 
        {
            System.out.println("error " + ex);
        }
    }//GEN-LAST:event_check_buttonMouseClicked

    private void about_menue_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_menue_itemActionPerformed
        JOptionPane.showMessageDialog(null,"Minecraft Username Check\n\nRaith Thomas 2012","About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_about_menue_itemActionPerformed

    private void close_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_buttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_close_buttonActionPerformed

    private void donate_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donate_itemActionPerformed
        try 
        {
            String os = System.getProperty("os.name");
            if (os != null && os.startsWith("Windows")) {
                Runtime.getRuntime().exec( "rundll32 url.dll,FileProtocolHandler "
                    + "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=F7U7X5YLSC3EC");
            } 
            else {
            Runtime.getRuntime().exec("firefox " + "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=F7U7X5YLSC3EC");
            }
        } 
        catch (IOException ioe) {
            System.out.println("error: " + ioe);
        }
    }//GEN-LAST:event_donate_itemActionPerformed

    private void license_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_license_itemActionPerformed
        License lic_window = new License();
        lic_window.setVisible(true);
    }//GEN-LAST:event_license_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MUC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MUC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MUC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MUC_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MUC_GUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_menue_item;
    private javax.swing.JButton check_button;
    private javax.swing.JLabel check_solution;
    private javax.swing.JMenuItem close_button;
    private javax.swing.JMenuItem donate_item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem license_item;
    private javax.swing.JTextField username_textfield;
    // End of variables declaration//GEN-END:variables
}
